app/__init__.py
import os

from flask import Flask, request, current_app, json
from flask_bootstrap import Bootstrap
from config import Config
from flask_pyoidc import OIDCAuthentication
from flask_pyoidc.provider_configuration import ProviderConfiguration, ClientMetadata


def parse_oidc_config(logout_uri):
    oidc_config=dict()
    with open('provider.json') as provider_file:
        provider_data = json.load(provider_file)
        for provider in provider_data:
            config = ProviderConfiguration(issuer=provider_data[provider]['issuer'],
                                           client_metadata=ClientMetadata(provider_data[provider]['client_id'],
                                                                          provider_data[provider]['client_secret'],
                                                                          post_logout_redirect_uris=[logout_uri + '/logout']))
            oidc_config.update({provider: config})
    return oidc_config


base_uri = os.environ.get("BASE_URI")
if not base_uri:
    raise ValueError("No BASE_URI environment set for application")
auth = OIDCAuthentication(parse_oidc_config(base_uri))

bootstrap = Bootstrap()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    bootstrap.init_app(app)
    auth.init_app(app)

    # init blueprints
    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, redirect, url_for, session, json

from app import auth
from app.main import bp
from flask_pyoidc.user_session import UserSession, UninitialisedSession


@bp.route('/index', methods=['GET', 'POST'])
@bp.route('/', methods=['GET', 'POST'])
def index():
    try:
        user_session = UserSession(session)
        is_authorized = user_session.is_authenticated()
    except UninitialisedSession:
        is_authorized = False
    return render_template('index.html',
                           title=('Home'),
                           authorized=(is_authorized),
                           )


@bp.route('/login')
@auth.oidc_auth('default')     # must match with provider name in provider.json!
def login():
    user_session = UserSession(session)
    user_session.update(access_token=user_session.access_token,
             id_token=user_session.id_token,
             userinfo=user_session.userinfo)
    return redirect(url_for('main.profile'))


@bp.route('/profile')
def profile():
    try:
        user_session = UserSession(session)
        is_authorized = user_session.is_authenticated()
    except UninitialisedSession:
        print("Not authenticated!")
        redirect(url_for('main.index'))
    return render_template('profile.html',
                           title=('Profile'),
                           access_token=user_session.access_token,
                           id_token=user_session.id_token,
                           userinfo=user_session.userinfo,
                           authorized=(is_authorized)
                           )

@bp.route('/logout_test')
@auth.oidc_logout
def logout():
    return render_template('logout.html',
                           title=('Logout')
                           )

app/templates/base.html
{%- extends "bootstrap/base.html" %}

{% block title %}
    {% if title %} {{ title }} {% else %}{{ _('Minimal Flask Example') }}{% endif %}
{% endblock %}

{% import "bootstrap/fixes.html" as fixes %}

{% block head %}
{{super()}}
{{fixes.ie8()}}
{%- endblock %}

{% block styles -%}
{{super()}}

<link rel="stylesheet" type="text/css"
      href="{{url_for('static', filename='mystyle.css')}}">
{% endblock %}


{% block navbar %}

<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Home</a>
            {% if authorized %}
                <a class="navbar-brand" href="{{ url_for('main.profile') }}">Profile</a>
                <a class="navbar-brand" href="{{ url_for('main.logout') }}">Logout</a>
            {% else %}
                <a class="navbar-brand" href="{{ url_for('main.login') }}">Login</a>
            {% endif %}
        </div>
    </div>
</nav>

{% endblock %}


{% block content %}
<div class="container">
    {% block app_content %}{% endblock %}
</div>
{% endblock %}


{% block scripts %}

{# <script src="{{url_for('.static', filename='myscripts.js')}}"></script> #}

{{super()}}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block app_content %}

<h1>Hello World!</h1>

{% endblock %}

app/templates/logout.html
{% extends "base.html" %}
{% block app_content %}

<h1>Your logged out!</h1>

{% endblock %}

app/templates/profile.html
{% extends "base.html" %}
{% block app_content %}

<h1>Profile</h1>

<h2>Access Token</h2>
{{ access_token }}

<h2>ID Token</h2>

{{ id_token }}

<h2>User Information</h2>

{{ userinfo }}

{% endblock %}